Disable undo in autogenerated state machines
hai-vr/av3-animator-as-code pull request #31
Opened 2022-09-11 01:13 UTC by bdunderscore

Unity's undo processing gets extremely slow when dealing with large numbers of newly created objects. I suspect there may be some O(n^2) scaling going on there. Regardless, this change disables undo for the AAC-handled state machines to avoid this issue.

2022-09-11 10:23 UTC, hai-vr commented
This seems consistent with what I observed in a non-backported change from CGE
https://github.com/hai-vr/combo-gesture-expressions-av3/commit/5bc9bfd6822ccde8eeda910e7e1882db3b0b7c96

Ref #24

2022-12-09 15:57 UTC, Happyrobot33 requested changes
Just needs a slight change to a type lookup, other than that this seems to work well and improves the build speed of the animator when there is alot of additions being made

2022-12-15 18:43 UTC, Happyrobot33 commented
This also needs to add in the undo change for AacFlCondition as those generate undo states aswell

2023-10-01 18:41 UTC, hai-vr commented
A similar fix was added to AAC V1:
https://github.com/hai-vr/av3-animator-as-code/blob/wip-v1/Packages/dev.hai-vr.animator-as-code.v1/V1/Editor/AacFlStates.cs#L189C38-L189C44

2023-10-01 18:41 UTC, closed without merging